theme: jekyll-theme-merlot
title: Froob's Labratory
description: This is where I will publish any projects I work on. Focuses include machine learning, natural language processing, text to speech, and more.
